Print multiple danfes on the same pdf file
asseinfo/br_danfe pull request #135
Opened 2021-05-31 14:50 UTC by alicehabitzreuter

2021-06-07 12:46 UTC, marcosdemelo commented
Olá @alicehabitzreuter, essa modificação vai quebrar a interface? Você vai subir uma major version?

2021-06-07 19:13 UTC, cesarjr requested changes

2021-06-07 19:13 UTC, cesarjr commented on lib/br_danfe/danfe_lib/nfe.rb
> +          initial_number_of_pages = @document.page_count
Remover as linhas 34, 36 e 38. Acho que esses espaços não estão agregando.

2021-06-07 19:13 UTC, cesarjr commented on spec/br_danfe/danfe_spec.rb
> +    it 'accepts a array of xmls' do
`it 'accepts an array of xmls' do` (an instead of a)

2021-06-07 19:50 UTC, alicehabitzreuter commented
> Olá @alicehabitzreuter, essa modificação vai quebrar a interface? Você vai subir uma major version?

@marcosdemelo essa modificação não quebra a interface, só permite receber mais de um xml.

2021-06-08 12:20 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfe.rb
> +        nfe_code = '55'
Lá na gem da NF-e, temos um definição centralizada desse número em `lib/nfe/models/NFe.rb`. Podemos usar de lá ou definir seguindo o mesmo padrão, o que acham?

2021-06-08 12:27 UTC, cesarjr commented on lib/br_danfe/danfe_lib/nfe.rb
> +        nfe_code = '55'
Isso não faria um projeto ser dependente do outro. Aquele projeto é fechado e este é open.

2021-06-08 12:28 UTC, cesarjr approved these changes

2021-06-08 12:34 UTC, merged