Add MDF-e DAMDFE
asseinfo/br_danfe pull request #146
Opened 2021-07-07 16:23 UTC by alicehabitzreuter

2021-07-08 15:08 UTC, marcosdemelo requested changes

2021-07-08 15:08 UTC, marcosdemelo commented on spec/br_danfe/mdfe_lib/header_spec.rb
> +    <<-eos
```suggestion
    <<~XML
      <?xml version="1.0" encoding="UTF-8"?>
        <mdfeProc xmlns="http://www.portalfiscal.inf.br/mdfe" versao="3.00">
        .
        .
        .
    XML
```

Aplicar nos demais se houver.

2021-07-08 15:08 UTC, marcosdemelo commented on spec/br_danfe/mdfe_lib/mdfe_identification_spec.rb
> +      	<MDFe xmlns="http://www.portalfiscal.inf.br/mdfe">
O que acham de mudar essa indentação para 2?

2021-07-08 15:08 UTC, marcosdemelo commented on lib/br_danfe/mdfe_lib/totalizer.rb
> +        cte_quantity
Não vamos ter CT-e.

2021-07-08 15:08 UTC, marcosdemelo commented on lib/br_danfe/mdfe_lib/totalizer.rb
> +          @pdf.stroke_color '000000'
Usaria a mesma recomendação anterior aqui.

2021-07-08 15:08 UTC, marcosdemelo commented on spec/br_danfe/mdfe_lib/totalizer_spec.rb
> +      <?xml version="1.0" encoding="UTF-8"?>
indentação

2021-07-08 15:08 UTC, marcosdemelo commented on spec/br_danfe/mdfe_lib/totalizer_spec.rb
> +      cte_quantity = "QTD. CTe\n18"
Não vamos ter CT-e.

2021-07-08 17:35 UTC, DouglasRochaT commented on lib/br_danfe/mdfe_lib/document.rb
> +      end
Precisamos deles para utilizar os métodos do Prawn.

2021-07-08 18:01 UTC, DouglasRochaT commented on lib/br_danfe/mdfe_lib/cep.rb
> +end
O que você acha de colocarmos essa classe como um método na classe helper da raiz?
Dessa forma ambos utilizariam esse método.

2021-07-08 18:06 UTC, marcosdemelo commented on lib/br_danfe/mdfe_lib/cep.rb
> +end
Acho que pode ser legal. Dai usaria aqui e na NF-e certo?

2021-07-08 18:07 UTC, DouglasRochaT commented on lib/br_danfe/mdfe_lib/cep.rb
> +end
Isso mesmo.

2021-07-16 20:25 UTC, marcosdemelo requested changes

2021-07-16 20:25 UTC, marcosdemelo commented on spec/br_danfe/mdfe_spec.rb
> +end
Falto imprimir essa parte:

![image](https://user-images.githubusercontent.com/1786713/126003096-413878ff-41a6-4a1a-a859-2038fe8d563d.png)

2021-07-16 20:25 UTC, marcosdemelo commented on spec/br_danfe/mdfe_spec.rb
> +end
Gerei um PDF manualmente e deu um treta, vejam que a placa ficou deslocada:

[test.pdf](https://github.com/asseinfo/br_danfe/files/6833163/test.pdf)

`$ irb -I lib -r 'br_danfe'`

```Ruby
xml = BrDanfe::XML.new(File.read('/Users/marcosdemelo/Downloads/MDF-e/10717781119000141580010000001211
000000003_v-procmdfe.xml'))

mdfe = BrDanfe::Mdfe.new(xml)

mdfe.save_pdf '/Users/marcosdemelo/Downloads/MDF-e/test.pdf'

```

2021-07-20 13:23 UTC, alicehabitzreuter commented on lib/br_danfe/danfe_lib/nfe_lib/emit_header.rb
> +          BrDanfe::Helper.format_cep(@xml['enderEmit/CEP'])
Tem um Helper mais específico para a NF-e com o mesmo nome, por isso tivemos que passar o caminho completo.
Se passarmos só Helper a classe pega a errada.

2021-07-20 13:23 UTC, alicehabitzreuter commented on lib/br_danfe/danfe_lib/nfe_lib/dest.rb
> +          BrDanfe::Helper.format_cep(@xml['enderDest/CEP'])
Tem um Helper mais específico para a NF-e com o mesmo nome, por isso tivemos que passar o caminho completo.
Se passarmos só Helper a classe pega a errada.

2021-07-20 13:56 UTC, alicehabitzreuter commented on lib/br_danfe/mdfe_lib/header.rb
> +        image.write(qrcode.as_png(module_px_size: 12).to_s)
A tag e o tamanho são diferentes, só se passarmos por parâmetro também.

2021-07-21 13:25 UTC, marcosdemelo commented on spec/br_danfe/mdfe_spec.rb
> +end
O meu xml estava com uma tags de reboque que não deveria existir. Tinha feito uma exemplo de uso e salvei sem querer.

2021-07-22 17:12 UTC, marcosdemelo requested changes

2021-07-22 17:12 UTC, marcosdemelo commented on lib/br_danfe/helper.rb
> +    def self.format_datetime_with_timezone(xml_datetime)
E se a gente não tivesse e método e sim criar um parâmetro no outro método chamado `format_datetime` chamado `with_time_zone: (false - padrão | true)`?

Inclusive o código daquele cara poderia ser assim:

```Ruby
xml_datetime.present? ? Time.parse(xml_datetime).strftime(format) : ''
```

Dai o `format` a gente vai ter o padrão e se for `with_time_zone`, adiciona o `%:z` no final. O que acham?

2021-07-22 17:12 UTC, marcosdemelo commented on lib/br_danfe/qr_code.rb
> +      @pdf.image image, width: @box_size, height: @box_size, position: :center
```suggestion
      @pdf.image(image, width: @box_size, height: @box_size, position: :center)
```

2021-07-22 17:12 UTC, marcosdemelo commented on spec/br_danfe/helper_spec.rb
> +      expect(described_class.format_cep('12345678')).to eq '12.345-678'
```suggestion
      expect(described_class.format_cep('12345678')).to eql '12.345-678'
```

Já recomendo trocar todos os `eq` nesses testes, se houverem....

2021-07-22 18:08 UTC, marcosdemelo approved these changes

2021-07-22 19:03 UTC, marcosdemelo approved these changes

2021-07-26 13:42 UTC, marcosdemelo approved these changes

2021-07-26 13:57 UTC, merged

2021-11-12 17:37 UTC, marcosdemelo commented
![image](https://user-images.githubusercontent.com/1786713/141510153-fbd82baf-1984-4ecd-8888-d5f66284bf4a.png)

2021-11-12 18:15 UTC, marcosdemelo commented
https://dfe-portal.svrs.rs.gov.br/mdfe/QRCode?chMDFe=32210717781119000141580010000001211000000003&tpAmb=1

![image](https://user-images.githubusercontent.com/1786713/141515002-d5a1259f-62df-4fd4-a334-60e502df883e.png)