Fixed installation instructions
asseinfo/br_danfe pull request #176
Opened 2022-08-12 20:56 UTC by taq

I think someone forgot some old code. :-)

2022-08-12 22:25 UTC, taq commented
Also, the way of #13 should be updated on README, replacing `logo_path` to `logo` and specifying `logo_dimensions` (I didn´t use it and got a 

```
logo_options.rb:20:in `dimensions': undefined method `>' for nil:NilClass (NoMethodError)
```

maybe it is a good idea to change constructor to

```ruby
   @logo_width  = logo_dimensions[:width]  || 0
   @logo_height = logo_dimensions[:height] || 0
```

to avoid the error above?

2022-08-29 13:39 UTC, marcosdemelo requested changes

2022-08-29 13:39 UTC, marcosdemelo commented on README.md
>          xml = File.read("nfe.xml")
Olá @taq, obrigado por sua contribuição.
Vou sugerir umas alterações para que o exemplo de uso fique ainda mais objetivo, de tal forma que não seja necessário nenhum recurso externo.
Aguardo seu ponto de vista e assim que você enviar os ajustes, já integro. Obrigado

```suggestion
        xml = File.read("spec/fixtures/nfe/v2.00/nfe_simples_nacional.xml")
```

2022-08-29 13:39 UTC, marcosdemelo commented on README.md
>          danfe.save_pdf("nfe.pdf")
```suggestion
        danfe.save_pdf("output.pdf")
```

2022-08-29 13:39 UTC, marcosdemelo commented on README.md
> +        danfe.options.logo_dimensions = { width: <largura>, height: <altura> }
```suggestion
        danfe.options.logo = "spec/fixtures/logo.png"
        danfe.options.logo_dimensions = { width: 100, height: 100 }
```

2022-08-30 10:37 UTC, taq commented on README.md
>          xml = File.read("nfe.xml")
Perfeito, quanto mais alterações ali para deixar mais certeiro, melhor. :-)

2022-08-30 12:17 UTC, merged