Add Canceled watermark support
asseinfo/br_danfe pull request #219
Opened 2024-07-26 21:12 UTC by wilfison

## Adiciona suporte a DANFE  cancelado

Adicionado um novo atributo `DanfeLib::Base#canceled` que define se deve mostrar a marca d'água "CANCELADO" no PDF. Suporte adicionado para NF-e e NFC-e.

Exemplo de uso:

```ruby
xml = File.read("spec/fixtures/nfe/v2.00/nfe_simples_nacional.xml")

danfe = BrDanfe::Danfe.new(xml)
danfe.canceled = true
danfe.save_pdf("output.pdf")
```

Foi  também uma transparência no `stamp` para permitir a leitura clara do conteúdo debaixo da marca.

2024-07-30 18:20 UTC, marcosdemelo requested changes

2024-07-30 18:20 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/base.rb
> +        @canceled = false
Olá Wilfison, esse tema de NF-e cancelada, é uma dúvida que já tenho a tempos. Nunca encontrei nada na documentação, e não quer dizer que não exista, uma forma de unir ou concatenar o evento de cancelamento ao XML autorizado.

Sei que seria possível implementarmos uma maneira de unir os dois XMLs, mas não acho que seria uma coisa legal sem que tenhamos como base uma pesquisa mais ampla. Caso não encontre documentação, em último caso, seria tentar identificar como a comunidade NF-e e automação comercial no Brasil lida com isso.

Digo isso, pois avaliamos aqui que o ideal seria o BRDanfe tomar essa decisão de imprimir a marca d'água, baseado no XML que ele vai gerar o PDF. No lugar de termos uma flag para isso.

2024-07-30 18:20 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfce.rb
>      end
Sobre a maneira como foi implementado a nova marca d'água, recomendo seguir o mesmo molde daquela que já existe hoje. Me avise caso tenha tentado isso e teve impedimentos.

E então, o código de impressão dessas 2 marcas d'água, podem ficar mais próximos. Onde, seria impresso `Cancelada` quando o XML tem autorização e evento de cancelamento. E `Sem valor fiscal` quando não tem autorização.

Algo parecido com isso:
```ruby
@document.stamp('canceled') if BrDanfe::Helper.canceled?(xml)

@document.stamp('has_no_fiscal_value') if BrDanfe::Helper.no_fiscal_value?(xml)
```

2024-07-31 23:59 UTC, wilfison commented on lib/br_danfe/danfe_lib/base.rb
> +        @canceled = false
@marcosdemelo Entendi, vou tentar pesquisar mais sobre.

2024-08-01 01:38 UTC, wilfison commented on lib/br_danfe/danfe_lib/base.rb
> +        @canceled = false
@marcosdemelo Pesquisei um pouco sobre o assunto e parece não haver uma forma oficial de em um único XML conter todos os dados da nota e do evento de cancelamento.

Dito isso, pensei em talvez fazer assim:

```ruby
nfe1 = File.read("nfe1.xml")
nfe1_evento = File.read("evento_nfe1.xml")

nfe2 = File.read("nfe2.xml")

# além de receber vários XMLs, também poderá receber vários eventos por XML
danfe = BrDanfe::Danfe.new([
  [nfe1, nfe1_evento],
  nfe2
])

danfe.save_pdf("output.pdf")
```

no código ficaria algo assim:

```ruby
def generate(footer_info)
  @xmls.each do |xmls|
    xml = xmls.is_a?(Array) ? xmls.first : xmls
    event_xmls = xmls.is_a?(Array) ? xmls[1..] : []
    
    # normal executing
    
    event_xmls.each do |event_xml|
      # executa alguma ação do evento
    end
  end
end
```

2024-08-03 20:16 UTC, wilfison commented on lib/br_danfe/danfe_lib/base.rb
> +      end
Foi adicionado esse método que agrupa os XMLs antes de gerar o PDF. Foi feito dessa forma para não quebrar o código antigo e para que mesmo se receber os XMLs fora de ordem, eles serão agrupados com seus respectivos eventos.

2025-05-20 12:33 UTC, closed without merging