Add new ship fields in br_danfe
asseinfo/br_danfe pull request #231
Opened 2024-10-15 18:02 UTC by MatCRL

2024-11-01 12:03 UTC, marcosdemelo requested changes

2024-11-01 12:04 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfe_lib/entrega.rb
> +        def self.can_render?(xml)
Acho que esse nome `has_delivery_local?` que tínhamos conversado no início ainda ficou melhor que `has_data?`.

2024-11-01 12:07 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfe_lib/entrega.rb
> +            xml_document.xpath('//xmlns:entrega/xmlns:xLgr', 'xmlns' => 'http://www.portalfiscal.inf.br/nfe').any?
```suggestion
            xml_document = Nokogiri::XML(xml)
            xml_document.xpath('//xmlns:entrega/xmlns:xLgr', 'xmlns' => 'http://www.portalfiscal.inf.br/nfe').any?
```

2024-11-01 12:22 UTC, MatCRL commented on lib/br_danfe/danfe_lib/nfe_lib/delivery.rb
> +        def can_render?
Ficou **delivery_local?**.

2024-11-01 13:32 UTC, marcosdemelo requested changes

2024-11-01 13:32 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfe_lib/entrega.rb
> +            xml_document.xpath('//xmlns:entrega/xmlns:xLgr', 'xmlns' => 'http://www.portalfiscal.inf.br/nfe').any?
```suggestion
          doc = xml.is_a?(BrDanfe::XML) ? xml : Nokogiri::XML(xml)
          doc.css('entrega/xLgr').text.present?
```

2024-11-01 13:55 UTC, marcosdemelo requested changes

2024-11-01 13:55 UTC, marcosdemelo commented on lib/br_danfe/danfe_lib/nfe_lib/entrega.rb
> +          if self.class.delivery_local?(@xml)
```suggestion
          if Entrega.delivery_local?(@xml)
```

2024-11-01 14:40 UTC, marcosdemelo requested changes

2024-11-01 14:40 UTC, marcosdemelo commented on spec/br_danfe/danfe_lib/nfe_lib/helper_spec.rb
> +      end
```suggestion
      let(:xml_street_entrega) { Nokogiri::XML(xml_entrega) }
```

2024-11-01 14:40 UTC, marcosdemelo commented on spec/br_danfe/danfe_lib/nfe_lib/entrega_spec.rb
> +      it 'returns false if has not entrega' do
```suggestion
      it 'returns false' do
```

2024-11-01 14:40 UTC, marcosdemelo commented on spec/br_danfe/danfe_lib/nfe_lib/entrega_spec.rb
> +
```suggestion
```

2024-11-04 12:50 UTC, marcosdemelo requested changes

2024-11-04 13:40 UTC, marcosdemelo requested changes

2024-11-04 13:40 UTC, marcosdemelo commented on spec/br_danfe/danfe_lib/nfe_lib/entrega_spec.rb
> +    context 'when recipient has CPF' do
Faltou remover esse ainda...

Dai depois disso, pode integrar e gerar a versão e atualizar no Fácil123.

2024-11-04 14:19 UTC, merged